### ISSUE TITLE
AddCycleGroup fails on vimRc

### ISSUE THREAD

**Issue by aemonge** [zef/vim-cycle#6]
Hi, I've just installed this plugin with Vundle. But vimrc won't reconize the `Unknown function: AddCycleGroup`

**Comment by zef** [comment]
I'm looking into this. I think it is not related to Vundle, but rather is some other issue. I'm not super with Vimscript but I'll see what I can do :smile:

**Comment by aemonge** [comment]
Thanks a lot !!!!! If I you need any help, don't hesitate on asking xD

**Comment by thynctank** [comment]
I can tell you I'm able to run `call AddCycleGroup` just fine in my .vimrc when loading it into MacVim, but terminal vim gives me this error. Is there something tied to gvim functionality?

I enjoy this plugin enough that I really want to make this work, so hopefully I can find some time to look into this in the near future. (I'm no vimscript genius either)

Oh and I use pathogen, not vundle. I have doubts it's tied to these at all.

Also, further confounding things, cycle is loaded even though my calls of `AddCycleGroup` failed. Meaning I can access help, toggle true/false and other built in cycles.

Hoping this may help put you on the scent, @zef.

**Comment by lleites** [comment]
I have a workaround for this but I  don't like it, this should be something not related to autocmd IMHO.
`autocmd VimEnter * call AddCycleGroup('xml.maven', ['-SNAPSHOT</', '</'])
`
This will add the cycle group once vim loads.

**Comment by aemonge** [comment]
Hi @lleites ,
I've tried that the following way, but it doesn't seams to work for me either, any suggestions ?

```
  autocmd VimEnter * call AddCycleGroup(['set', 'get']
    \ ,['push', 'pop']
    \ ,['mas', 'menos']
    \ ,['prev', 'next']
    \ ,['start', 'end']
    \ ,['read', 'write']
    \ ,['truthy', 'falsy']
    \ ,['filter', 'reject']
    \ ,['internal', 'external']
    \ ,['short', 'normal', 'long']
    \ ,['subscribe', 'unsubscribe']
    \ ,['header', 'body', 'footer']
    \ ,['protected', 'private', 'public']
    \ ,['red', 'blue', 'green', 'yellow']
    \ ,['tiny', 'small', 'medium', 'big', 'huge']
    \ ,['pico', 'nano', 'micro', 'mili', 'kilo', 'mega', 'giga', 'tera', 'peta']
    \ ,['sunday', 'monday', 'tuesday', 'wensday', 'thursday', 'friday', 'saturday']
    \ )
```

**Comment by lleites** [comment]
Reading the code of AddCycleGroup it seems that you need one call per group.

**Comment by AlexAxthelm** [comment]
`Plug` user here. I'm getting this issue in both terminal and gvim on Windows 10.

**Comment by aemonge** [comment]
Please try like this to see if it works:

```
      au VimEnter * call AddCycleGroup(['set', 'get'])
      au VimEnter * call AddCycleGroup(['form', 'to'])
      au VimEnter * call AddCycleGroup(['push', 'pop'])
      au VimEnter * call AddCycleGroup(['mas', 'menos'])
      au VimEnter * call AddCycleGroup(['prev', 'next'])
      au VimEnter * call AddCycleGroup(['start', 'end'])
      au VimEnter * call AddCycleGroup(['light', 'dark'])
      au VimEnter * call AddCycleGroup(['open', 'close'])
      au VimEnter * call AddCycleGroup(['read', 'write'])
      au VimEnter * call AddCycleGroup(['truthy', 'falsy'])
      au VimEnter * call AddCycleGroup(['filter', 'reject'])
      au VimEnter * call AddCycleGroup(['internal', 'external'])
      au VimEnter * call AddCycleGroup(['short', 'normal', 'long'])
      au VimEnter * call AddCycleGroup(['subscribe', 'unsubscribe'])
      au VimEnter * call AddCycleGroup(['header', 'body', 'footer'])
      au VimEnter * call AddCycleGroup(['protected', 'private', 'public'])
      au VimEnter * call AddCycleGroup(['red', 'blue', 'green', 'yellow'])
      au VimEnter * call AddCycleGroup(['tiny', 'small', 'medium', 'big', 'huge'])
      au VimEnter * call AddCycleGroup(['pico', 'nano', 'micro', 'mili', 'kilo', 'mega', 'giga', 'tera', 'peta'])
      au VimEnter * call AddCycleGroup(['sunday', 'monday', 'tuesday', 'wensday', 'thursday', 'friday', 'saturday'])
```
